### ISSUE TITLE
lock an image ( or div ) into view for a few scrolling seconds 

### ISSUE THREAD

**Issue by halukkaramete** [nateplusplus/pushIn-js#2]
Hi, 

I've seen your parallax script. 
Like in many parallax scripts, it too misses one interesting feature: that is to fix an image to screen a for a few scrolling seconds... 
Please visit the Mayweather's page as it does it very well. You will need to scroll a while to get to the sticky parallax section. 
http://www.espn.com/espn/feature/story/_/id/12748163/floyd-mayweather-prepares-2-fight-seal-legacy

Could you tell me if your script can adjust to creating this effect? 

All parallaxers I've seen so far lacks this feature, which I think is very interesting.

**Comment by nateplusplus** [comment]
Hi @halukkaramete thanks for writing me and sorry for not responding sooner! Honestly, I wrote this plugin for myself as a beginner coder and I'm just now realizing so many people have starred this - I'm very surprised! 😅 

Definitely keep in touch if you'd like to collaborate on more parallax stuff, I am still very interested in these effects.

I'm going to close this issue for now.
