### ISSUE TITLE
Scale of elements

### ISSUE THREAD

**Issue by gabrielb86** [nateplusplus/pushIn-js#22]
Hi Nate, awesome work!

I'm having issues understanding how the script works:

I would like that some elements grow bigger than they do on scroll. I've been playing with the attributes (datepushin-from, datepushin-to, datepushin-speed) but I still don't get the desired effect. Using Developers tools how on scroll the CSS scale property is changed, but I'm stuck beyond that.

Could you please tell me If I'm missing or misunderstanding something? Thanks! Have a great day.

**Comment by nateplusplus** [comment]
Hi @gabrielb86, I am happy to help.

Make sure you double-check the spelling of those attributes. It should be: `data-pushin-to`, `data-pushin-from` and `data-pushin-speed`.

Let me know if that helps.

**Comment by gabrielb86** [comment]
Thanks Nate! That helped! 👍
