### ISSUE TITLE
error on line 91

### ISSUE THREAD

**Issue by ghost** [nateplusplus/pushIn-js#3]
I'm not sure why this error occurs, I thought I'd submit my failure to launch. scaleArray seems to be undefined on scroll (line 91 of pushIn.js). Screenshot included.
![Screenshot from 2019-09-04 01-37-16](https://user-images.githubusercontent.com/47752559/64228535-2c59dd00-ceb5-11e9-951b-35bb9dbe0322.png)

**Comment by nateplusplus** [comment]
Thanks for letting me know, @benmfoster! Sorry for the delay – I did not realize others were using this code and just now looking back at this project. I'll take a look and see if I can fix this.

**Comment by nateplusplus** [comment]
This should be fixed with v2 release.

Closing this ticket.

Thanks!!
