### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by singhayushh** [nateplusplus/pushIn-js#4]
Hi, I set the plugin as mentioned in the ReadME.
IDK, a horizontal scroll bar is coming up after scrolling a few pixels followed by the elements coming up enlarged.

**Comment by nateplusplus** [comment]
Hi @singhayushh sorry for not responding sooner. I wrote this code as a newbie and now realize other people have written me some awesome issues! I hope to look back at this old repository and clean it up a bit.

I tested this out in my browser and I am not seeing a horizontal scrollbar. Can you let me know more about how you reproduced this issue?

Thanks!

**Comment by singhayushh** [comment]
Greetings!

I don't a clear recollection of this issue but as far as I remember, I think this issue was caused due to a flex container that I was using to wrap the div and the workaround was to add another (non flex) wrapper.

You may proceed to close this issue.

**Comment by nateplusplus** [comment]
@singhayushh Ah ok, got it. Thanks for following up! I will go ahead and close this.
