### ISSUE TITLE
Support multiple module formats

### ISSUE THREAD

**Issue by arturovt** [nateplusplus/pushIn-js#73]
We currently use Webpack for building this library and it emits bundle in the UMD format. Webpack is considered to be used in applications, but not for building libraries.

We have to consider switching to Rollup to be able to publish this library in the following formats:

- ESM (path to the file will be added to the `package.json[module]` property)
- SystemJS
- CommonJS

Webpack's support for ESM is still experimental.

The SystemJS loader is a widely used module loader and consumers will be able to load this library in the following way:
```js
System.import('pushin').then(...);
```

**Comment by nateplusplus** [comment]
@arturovt this is really interesting and sounds like a great addition. To be honest, I don't have much experience building modules in multiple formats, so I would be very interested to see your approach to this solution, if you are up for tackling this?

Question: You mentioned that "Webpack is considered to be used in applications, but not for building libraries" – Is there a better alternative to webpack that we should consider?

**Comment by arturovt** [comment]
Yeah, Rollup is a great solution for libraries.

Sure, I can take that.

**Comment by nateplusplus** [comment]
Doing some reading up on this and Rollup sounds so much better! Looking forward to seeing what you come up with.
